 nolabels:true$
 display2d:false$
 load("mactex.lisp")$
 set_plot_option([run_viewer, false])$
 set_tex_environment_default("","")$
 lbrace:"{"$
 rbrace:"}"$
 file_output_append:false$
 with_stdout("Maxiplot-eksempel-med-GNUPlot.mxp")$
 file_output_append:true$ 
load("mactex-utilities.lisp")$

with_stdout("Maxiplot-eksempel-med-GNUPlot.mxp", print("\\gdef\\mxpi",lbrace),
tex(solve(2*x^2-2=-3*x^2+4,x))

,print(rbrace))$
